### ISSUE TITLE
Kubeflow installation fails if ksonnet is not installed

### ISSUE THREAD

**Issue by realvz** [mreferre/ekstender#2]
Before installing kubeflow, the script needs to check if ksonnet is installed, if not, it should install ksonnet otherwise kubeflow app deployment will fail.

**Comment by mreferre** [comment]
Indeed. However I prefer NOT to mess with the system EKStender is running on. It does require a bunch of stuff to work (AWS CLI, jq, ksonnet etc). I am actually adding the requirements to [eksutils](https://github.com/mreferre/eksutils) which is the tool I am suggesting to use to run EKStender.
